require: 
 - rubocop-rake

AllCops:
  NewCops: enable

Metrics/ModuleLength:
  Max: 200

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  IgnoredMethods:
    - class_methods

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - class_methods
